spring:
  jwt-secret-key: secret
  cookie-name: SESSION

  datasource:
    url: jdbc:postgresql://localhost/users
    username: postgres
    password:

  redis:
    database: 0
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: localhost
    port: 1025
    username: test
    password: test

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#server:
#  ssl:
##    key-alias: localhost
##    key-password: HotGarbage
#    key-store: classpath:localhost-ssl.p12
#    key-store-password: HotGarbage
#    client-auth: NEED